module Ruby
  module Three
    module Sample
      VERSION: String
      # See the writing guide of rbs: https://github.com/ruby/rbs#guides

      class Error < StandardError
      end

      # https://github.com/ruby/rbs#rbs サンプル
      class User
        attr_reader login: String
        attr_reader email: String

        def initialize: (login: String, email: String) -> void
      end

      class Bot
        attr_reader name: String
        attr_reader email: String
        attr_reader owner: User

        def initialize: (name: String, owner: User) -> void
      end
    end
  end
end
