module Ruby
  module Three
    module Sample
      VERSION: String
      # See the writing guide of rbs: https://github.com/ruby/rbs#guides

      class Error < StandardError
      end
    end
  end
end
