module Ruby
  module Three
    module Sample
      VERSION: String
      # See the writing guide of rbs: https://github.com/ruby/rbs#guides

      class Error < StandardError
      end

      # https://github.com/ruby/rbs#rbs サンプル
      class User
        @login: String
        @email: String

        def initialize: (String from, String email) -> void
        def login=: (String) -> void
        def email=: (String) -> void
      end
    end
  end
end
